version: "3"
services:
  golang:
    container_name: api-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: ["./main"]
    networks:
      - kong-net
  kong-gateway:
    image: kong/kong-gateway:3.7.1.2
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    volumes:
      - ./kong/declarative:/kong/declarative/
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    networks:
      - kong-net

networks:
  kong-net:
    external: false